#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

function zupgrade {
	~/.zprezto/go.sh
}

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vi'
export VISUAL='mate -w'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

if type "brew" > /dev/null; then

  # GO
  export GOPATH=$(brew --prefix)/opt/go
  path=(
    $GOPATH/bin
    ~/.composer/vendor/bin
    $path
  )

  # NPM
  if type "npm" > /dev/null; then
    path=(
      $(brew --prefix)/share/npm/bin
      $path
    )
  fi

  # COMPOSER
  if type "composer" > /dev/null; then
    path=(
      ~/.composer/vendor/bin
      $path
    )
  fi

  path=(
    $(brew --prefix)/{bin,sbin}
    $path
  )

fi

# Set the list of directories that Zsh searches for programs.
path=(
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

# export DOCKER_HOST=tcp://127.0.0.1:2375
# export SSL_CERT_FILE=/usr/local/opt/curl-ca-bundle/share/ca-bundle.crt
