#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source aliases
if [ -f ~/.aliases ]; then
    . ~/.aliases
fi

if [ -f ~/.alias ]; then
    . ~/.alias
fi

# Customize to your needs...
